### ISSUE TITLE
Make wait() compatible with global setTimeout stub

### ISSUE THREAD

**Issue by scottmas** [axios/moxios#12]
Many stubbing libraries (SinonJS in particular) provide a handy way to stub out built in date and timers. In Sinon this is `sinon.useFakeTimers()`. However, since the `wait()` function internally uses setTimeout, you have to manually increment the clock in order to get the `wait()` callback to fire, which is annoying.

**Comment by aphofstede** [comment]
Here's an example: https://stackoverflow.com/questions/47907000/testing-debounced-asynchronous-request-with-moxios-and-faketimers
Workaround also welcome.
