### ISSUE TITLE
Installing/Uninstalling like the README states doesn't mock requests properly

### ISSUE THREAD

**Issue by rfgamaral** [axios/moxios#19]
I've tried to follow the documentation but for some reason can't get this ti work properly. If relevant, I'm using TypeScript, React and Jest with Enzyme.

I have something like this on my app:

```ts
public componentWillMount(): void {
    Axios.get("https://hostname/token")
        .then((response) => {
            console.log(response);
        })
        .catch((error) => {
            console.log(error);
        });
}
```

And this is my simple test spec:

```ts
import * as React from "react";
import * as Moxios from "moxios";

import { shallow } from "enzyme";

import Application from "components/Application";

describe("Application", () => {

    beforeEach(() => {
        Moxios.install();
    });

    describe("#render", () => {

        test("application renders correctly", () => {
            Moxios.stubRequest("https://hostname/token", {
                status: 200,
                responseText: {}
            });

            expect(shallow(<Application />)).toMatchSnapshot();
        });

    });

    afterEach(() => {
        Moxios.uninstall();
    });

});
```

I should be getting output from the `console.log(response);` but I don't. **I can only get this working if I remove the `Moxios.uninstall()` line from `afterEach`.** I've also tried other variations like `beforeAll` / `afterAll` but to no avail.

For now, since I can't call `Moxios.uninstall()` on my tests, I've just removed `beforeEach` / `afterEach` completely and I'm calling `Moxios.install()` inside the first `describe`. But this doesn't fell right.

What might I be doing wrong?

What am I doing wrong?

**Comment by vidhill** [comment]
Experiencing similar issue..

However, I'm running uninstall in a before() and after() not afterEach
