### ISSUE TITLE
Create new build with stubtimeout

### ISSUE THREAD

**Issue by andrenanninga** [axios/moxios#22]
I'm trying to use `stubtimeout` in version `0.3.0` but it doesn't seem to be included in the `dist` files.

Am I missing something or is it not present in the build of `0.3.0`?

**Comment by seanohue** [comment]
It definitely is not in 3.0.0.

Seconding this, it would be really handy. I tried to point the `package.json` to the most recent commit but it still isn't in dist.

**Comment by anilanar** [comment]
Kamino cloned this issue to anilanar/moxios
