### ISSUE TITLE
stubOnce behavior / documentation

### ISSUE THREAD

**Issue by timm-gs** [axios/moxios#42]
The docs for `stubOnce` state: "Stub a response to be used one or more times to respond to a request matching a method and a URL or RegExp.".

From the method name I was expected a different behavior, namely that the response would only used once and subsequent requests would fail.

**Comment by nicosommi** [comment]
As I want to test a retry mechanism and the error handling regarding that, I also found it confusing since I thought that I was covered with that method.

Anyways, if anyone interested, you can do this by actually manipulating the stubs array right on the main moxios instance.
E.g.
```
        moxios.stubOnce(
          'put',
          'http://myapi/products/1',
          {}
        )

        let obj = moxios.stubs.mostRecent()
        let count = 0
        Object.defineProperty(obj, 'response', {
          get: () => {
            count++
            if (count > 1) {
              return { status: 200, response: '' }
            }
            return { status: 500, response: '' }
          }
        })
```
Or maybe is a better way already to do this.
Otherwise I can prepare a PR for this if maintainers are interested @mzabriskie

**Comment by anilanar** [comment]
Kamino cloned this issue to anilanar/moxios

**Comment by mrjacobbloom** [comment]
I assumed this function would let me temporarily override an existing stub in the middle of our test suite. Here was what I did instead, in case it helps anyone else:

```javascript
function overrideStub(url, response) {
    const l = moxios.stubs.count();
    for (let i = 0; i < l; i++) {
        const stub = moxios.stubs.at(i)
        if (stub.url === url) {
            const oldResponse = stub.response;
            const restoreFunc = (() => stub.response = oldResponse);

            stub.response = response;
            return restoreFunc;
        }
    }
}

const restoreStub = overrideStub("../api/foo", {
    status: 500,
    response: 'An error occurred : Bar baz.'
});

buttonThatExpectsError.click();

moxios.wait(() => {
    assert(....);
    restoreStub();
})
```
