### ISSUE TITLE
Tracking what Requests are called with

### ISSUE THREAD

**Issue by joelzimmer** [axios/moxios#46]
I'd like to mimic something like what [`jest#wasCalledWith`](https://facebook.github.io/jest/docs/en/expect.html#tohavebeencalledwitharg1-arg2-) does so I can verify that a call was requested with the correct data. Is that currently possible? The only insight we have into that at the moment is that a URL may have been updated if it contained `params` that were interpolated

**Comment by anilanar** [comment]
Kamino cloned this issue to anilanar/moxios
