### ISSUE TITLE
Feature: Method getLast for moxios.requests

### ISSUE THREAD

**Issue by fenderil** [axios/moxios#47]
Hello there.

It will be cool to add method getLast, that takes reverse array of moxios.requests and returns last of found.

It is valuable as mostRecent method in cases with splitting multiple logic inside moxios.wait method.

Example:
```
moxios.wait(() => {
  moxios
    .requests
    .getLast('post', '/foo')
    .respondWith(fooResponse)
    .then(doSomething)

  moxios
    .requests
    .getLast('post', '/bar')
    .respondWith(barResponse)
    .then(doSomething)
})
```

**Comment by anilanar** [comment]
Kamino cloned this issue to anilanar/moxios
