### ISSUE TITLE
Wildcard Mock Not Working

### ISSUE THREAD

**Issue by AdrianHL** [axios/moxios#60]
Hi,

I have some tests that require wildcards (see example below) but it doesn't look to be working as expected (the requests is not mocked).

`moxios.stubRequest('/comments/.*/vote', {
        status: 200,
        response: {
            success: true
        }
    })`

Any idea why this could be happening?

Thanks in advance

**Comment by guilhermemj** [comment]
Hi mate!

I may be wrong, but I think wildcards should be RegExp, not strings, as in the example from README:

``` javascript
 // Alternatively URL can be a RegExp
 moxios.stubRequest(/say.*/, {/* ... */})
```

Try using `/comments\/.*\/vote/` (without quotes).
