### ISSUE TITLE
why catch method is not invoked?

### ISSUE THREAD

**Issue by scrafy** [axios/moxios#62]
test('should fails with incorrect secret_key', (done) => {

            const errorResp = {
                status: 422,
                response: mock_objects.auth_inv_secret
            };
            conf.secret_key = 'aaabbb';
            let api = new ApiRequest(conf);
            api.Auth(); //call to backend 

            moxios.wait(function () {
                let request = moxios.requests.mostRecent();
                request.reject(errorResp);
            }).catch(error => {
                console.log(error);
                done();
            });
        });

Testing with jest i get -> TypeError: Cannot read property 'catch' of undefined

**Comment by sstraatemans** [comment]
bump

**Comment by dbeff** [comment]
I had the same issue @scrafy, did you find any solution for it?

**Comment by dbeff** [comment]
The only way that I was able to make it works was: 

```javascript
moxios.wait(() => {
      const request = moxios.requests.mostRecent();
      request.respondWith({ status: 400 }).then(() => {
        try {
          // assert something
          done();
        } catch (err) {
          done.fail(err);
        }
      });
    });
```

**Comment by enriqg9** [comment]
> The only way that I was able to make it works was:
> 
> ```js
> moxios.wait(() => {
>       const request = moxios.requests.mostRecent();
>       request.respondWith({ status: 400 }).then(() => {
>         try {
>           // assert something
>           done();
>         } catch (err) {
>           done.fail(err);
>         }
>       });
>     });
> ```

This causes my tests to fail:
`Error: Request failed with status code 400`

If I use `response.reject(...).then()` or `response.reject(...).catch()` as the docs show, I get respectively:
`TypeError: Cannot read property 'then' of undefined`
`TypeError: Cannot read property 'catch' of undefined`

I cannot test for rejected responses using Moxios + Jest
