### ISSUE TITLE
request.reject undefined (using typescript)

### ISSUE THREAD

**Issue by dbeff** [axios/moxios#68]
Following the example below from the `README.de` file, I'm getting `request.reject` equal to `undefined`. The only way that I was able to mock an error on the request was by using `respondWith` passing status `4xx`. Am I doing something wrong?

```javascript
moxios.wait(function () {
  let request = moxios.requests.mostRecent()
  request.reject(errorResp)
  }).catch(function (err) {
    equal(err.status, errorResp.status)
    equal(err.response.message, errorResp.response.message)
    done()
  })
})
```

**Comment by seemranxec** [comment]
I'm facing the same issue, did you manage to figure what was going wrong ?

**Comment by yuri-gagarin** [comment]
seems like no type definition for moxios.reject()
